version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/react-amphtml
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-
      - run: npm install
      - run: npm run codegen
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test
      - save_cache:
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
